#!/usr/bin/env sh
if is_command yay; then
    yay -Yc
fi
if is_command flatpak; then
    flatpak uninstall --unused
fi
if is_command paccache; then
    paccache --remove --uninstalled --keep 0
    paccache --remove --keep 3
fi
