#!/usr/bin/env sh
set -x # echo the commands are are being run

disk() {
    if is_command dysk; then
        # Default cols is fs+type+disk+used+use+free+size+mp
        dysk --cols=fs+used+use+free+size+mp
    elif is_command df; then
        df --human-readable --exclude-type=tmpfs --total
    fi
}

disk

if is_command yay; then
    yay -Yc
    yay -Sc
fi
if is_command flatpak; then
    flatpak uninstall --unused
fi
if is_command paccache; then
    paccache --remove --uninstalled --keep 0
    paccache --remove --keep 3
fi

disk
