#!/usr/bin/env bash
if ! is_command ffprobe; then
    >&2 echo 'codec requires ffprobe'
    exit 4
elif ! is_command grep; then
    >&2 echo 'codec requires grep'
elif (( $# == 0 )); then
    >&2 echo 'Expected a video or audio file as an argument but got zero arguments'
    exit 1
fi
for arg in "$@"; do
    if [ ! -f "$arg" ]; then
        >&2 echo "$arg is not a valid file"
        exit 3
    fi
    ffprobe -i "$arg" 2>&1 |
        grep --extended-regexp --only-matching '(Video|Audio): [^(,]+' | while read -r line; do
            tstyle green
            echo -n "$arg: "
            tstyle reset
            echo "$line";
        done
done
