#!/usr/bin/env bash

if ! is_command yt-dlp; then
    >&2 echo "dl requires yt-dlp"
    exit 1
fi

if [ ! -w . ]; then
    >&2 echo "You do not have write permission in this directory"
    exit 2
fi

for arg in "$@"; do
    if ! yt-dlp --write-auto-subs --write-subs "$arg"; then
        yt-dlp "$arg"
    fi
    yt-dlp -i --get-filename --skip-download "$arg" | while read -r filename; do
        if is_command chat_downloader; then
            # https://github.com/xenova/chat-downloader with patches found in issues
            wle="$(echo "$filename" | without_last_extension)"
            tee_file="$wle.chat.txt"
            chat_downloader "$arg" | tee "$tee_file"
            if [ ! -s "$tee_file" ]; then
                rm "$tee_file"
            fi
        fi
        if ! ls "$wle.en"* 1>/dev/null 2>&1; then
            transcribe "$filename"
        fi
    done
done
