#!/usr/bin/env bash
if ! is_command ffmpeg; then
    >&2 echo 'duration requires ffmpeg'
    exit 4
elif ! is_command grep; then
    >&2 echo 'duration requires grep'
    exit 5
elif (( $# == 0 )); then
    >&2 echo 'Expected a video or audio file as an argument but got zero arguments'
    exit 1
elif (( $# > 1 )); then
    >&2 echo 'Expected only one argument (a video or audio file) but got multiple'
    exit 2
elif [ ! -f "$1" ]; then
    >&2 echo "$1 is not a valid file"
    exit 3
fi
ffmpeg -i "$1" 2>&1 | grep --basic-regexp --only-matching 'Duration: [0-9.:]\+' | grep --basic-regexp --only-matching ' [0-9.:]\+' | grep --color=never --basic-regexp --only-matching '[0-9.:]\+'
