#!/usr/bin/env bash

if ! is_command jq; then
    >&2 echo 'edchat reqiures jq'
    exit 1;
fi

color_orange="$(tstyle -t 208)"
color_wing="$(tstyle -t brightcyan)"
color_squadron="$(tstyle -t brightgreen)"
color_direct="$(tstyle -t 215)"
color_reset="$(tstyle reset)"

tail -f $HOME/.steam/steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved\ Games/Frontier\ Developments/Elite\ Dangerous/* 2>/dev/null | grep --line-buffered '"ReceiveText"' | while read -r line; do
    if [ "$(echo "$line" | jq ".Message_Localised")" = "null" ]; then
        channel_raw="$(echo "$line" | jq -r ".Channel")"
        case "$channel_raw" in
            wing) channel='WING';color="$color_wing" ;;
            local) channel='LOCAL';color="$color_orange" ;;
            squadron) channel='SQUADRON';color="$color_squadron" ;;
            starsystem) channel='SYSTEM';color="$color_orange" ;;
            player) channel='DIRECT';color="$color_direct" ;;
            *) channel="$channel_raw";color=''; ;;
        esac
        from="$(echo "$line" | jq -r ".From")"
        message="$(echo "$line" | jq -r ".Message")"
        echo "$color[$channel] [$from]: $message$color_reset"
    fi
done

