#!/usr/bin/env bash
if ! is_command ffmpeg; then
    >&2 echo 'fps requires ffmpeg'
    exit 4
elif ! is_command grep; then
    >&2 echo 'fps requires grep'
elif (( $# == 0 )); then
    >&2 echo 'Expected a video or audio file as an argument but got zero arguments'
    exit 1
fi
for arg in "$@"; do
    if [ ! -f "$arg" ]; then
        >&2 echo "$arg is not a valid file"
        exit 3
    fi
    if (( $# > 1 )); then
        tstyle green
        echo -n "$arg: "
        tstyle reset
    fi
    ffmpeg -i "$arg" 2>&1 | grep --basic-regexp --only-matching '[0-9.]\+ fps' | grep --color=never --basic-regexp --only-matching '[0-9.]\+'
done
