#!/usr/bin/env sh

export PATH="$HOME/.cargo/bin:$PATH" # So it has access to tstyle

# This thing isn't perfect, but I have spent hours improving it, it works good enough, I'm happy with it

# list all files, only get the ones that have a dot in them that isn't at the start, and only get everything before that first non-start dot
files_with_dots_without_dots=$(ls | grep -v / | grep '.\.' | sed -E 's/(.)\..*/\1/');

bold="$(tstyle -t bold)"
blue="$(tstyle -t blue)"
magenta="$(tstyle -t magenta)"
reset="$(tstyle -t reset)"

# Go through all of those, remove duplicates ("abc.txt" and "abc.mp4" both become "abc")
echo "$files_with_dots_without_dots" | uniq | while read uniq_file_start ; do
    # Make directory with that file-extension-less name
    echo "Making directory ${blue}${bold}${uniq_file_start}${reset}";
    mkdir "$uniq_file_start";

    # Save the length of that string for later
    len=${#uniq_file_start};

    # Get all files that have that file-extension-less name in it
    files_with_start=$(ls -p | grep -v / | grep --fixed-strings "$uniq_file_start");

    # iterate through those
    echo "$files_with_start" | while read file ; do

        # make sure it actually starts with it
        sliced=${file:0:$len};
        if [ "$sliced" == "$uniq_file_start" ]; then

            # Move the file into to created folder
            echo "Moving ${magenta}${bold}${file}${reset} into ${blue}${bold}${uniq_file_start}${reset}"
            mv "$file" "$uniq_file_start"
        fi
    done
done
