#!/usr/bin/env sh

if ! is_command eza; then
    >&2 echo "isolate requires eza (I know, it's not a very portable script)"
    exit 1
elif ! is_command rg; then
   >&2 echo "isolate requires ripgrep (I know, it's not a very portable script)"
    exit 2
fi

# This thing isn't perfect, but I have spent hours improving it, it works good enough, I'm happy with it

# list all files, only get the ones that have a dot in them that isn't at the start, and only get everything before that first non-start dot
files_with_dots_without_dots=$(eza --only-files --no-quotes | rg --only-matching "^(.+?)\." --replace='$1');

bold="$(tput bold)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
reset="$(tput sgr0)"

# Go through all of those, remove duplicates ("abc.txt" and "abc.mp4" both become "abc")
echo "$files_with_dots_without_dots" | uniq | while read uniq_file_start ; do
    # Make directory with that file-extension-less name
    echo "Making directory ${blue}${bold}${uniq_file_start}${reset}";
    mkdir "$uniq_file_start";

    # Save the length of that string for later
    len=${#uniq_file_start};

    # Get all files that have that file-extension-less name in it
    files_with_start=$(eza --only-files --no-quotes | rg --fixed-strings "$uniq_file_start");

    # iterate through those
    echo "$files_with_start" | while read file ; do

        # make sure it actually starts with it
        sliced=${file:0:$len};
        if [ "$sliced" == "$uniq_file_start" ]; then

            # Move the file into to created folder
            echo "Moving ${magenta}${bold}${file}${reset} into ${blue}${bold}${uniq_file_start}${reset}"
            mv "$file" "$uniq_file_start"
        fi
    done
done
