#!/usr/bin/env bash
function menu {
    rofi -dmenu -show-icons -no-custom -i -theme gruvbox-dark -font "JetBrainsMonoNF 13" -p "$1" -no-fixed-num-lines || exit 0
}

function text_input {
    echo "" | rofi -dmenu -theme-str 'listview { enabled: false;}' -theme gruvbox-dark -font "JetBrainsMonoNF 13" -p "$1" || exit 0
}

left_monitor='output HDMI-A-1'
right_monitor='output DisplayPort-1'

function balatro_mod {
    local dir="$HOME/.local/share/Steam/steamapps/common/Balatro"
    case "$(echo -e "Enable\nDisable" | menu 'Balatro Modloader')" in
        Enable) mv "$dir/version.dll.disabled" "$dir/version.dll" && notify-send 'Balatro Modloader Enabled';;
        Disable) mv "$dir/version.dll" "$dir/version.dll.disabled" && notify-send 'Balatro Modloader Disabled';;
        *) exit 1
    esac
}

function direwolf {
    i3-msg "workspace number 2;move workspace to $right_monitor;exec firefox https://www.youtube.com/@direwolf20/videos"
    i3-msg "workspace number 3;move workspace to $left_monitor;exec prismlauncher --launch 'FTB StoneBlock 4'"
}

function minecraft {
    local instance="$(ls -d ~/.local/share/PrismLauncher/instances/*/ | while IF= read -r dir; do
        local name="$(echo "$dir" | sed 's/.\+instances\///' | sed 's/\/$//')"
        printf "%s" "$name"
        printf "\0icon\x1f%sminecraft/icon.png\n" "$dir"
    done | menu)"
    if [[ -z "$instance" ]]; then exit 0; fi
    prismlauncher --launch "$instance"
}

function resend_notif {
    count="$(text_input "How many notifications?")"
    resend_notification "$count"
}

function startup {
    # Before launching Discord and Thunderbird, applications that require internet access, make sure there is internet access. Wait up to 5 seconds for it.
    # (Stops waiting right away if there is a connection)
    if ! nm-online -t 5; then
        # If there isn't internet access even after 5 seconds
        notify-send "Startup failed because of lack of internet access"
        exit
    fi
    i3-msg "workspace number 2;move workspace to $left_monitor"
    i3-msg "workspace number 1;move workspace to output $right_monitor;exec discord;exec thunderbird"
    i3-msg 'workspace number 2' # Workspace 2 is on the left, but the current workspace on the left monitor will be workspace 3. This makes workspace 2 the active workspace on the left monitor
    i3-msg 'workspace number 1' # Focus workspace 1 so Discord opens in the correct workspace since it likes to launch a window, wait, close it, then launch another window
}


function socialmedia {
    firefox -new-tab 'https://www.facebook.com/?sk=h_chr' -new-tab 'https://mastodon.sdf.org/home' -new-tab 'https://bsky.app/' &
}

function timer {
    local name
    local duration
    name="$(text_input "Timer Name")"
    duration="$(text_input "Timer Duration")"
    if echo "$duration" | grep -Pv "^((\d+[smhd])|((\d+[smhd] )+(\d+[smhd])))$"; then
        notify-send "Invalid Duration"
    else
        sleep $duration
        notify-send -t 0 -u critical "$name timer finished after $duration"
        spd-say "$name timer finished"
    fi
}

case "$(echo -e "Balatro Modloader\ndirewolf20\nMinecraft\nResend Notifications\nSocial Media\nStartup\nTimer" | menu)" in
    'Balatro Modloader') balatro_mod ;;
    direwolf20) direwolf ;;
    Minecraft) minecraft ;;
    'Resend Notifications') resend_notif ;;
    'Social Media') socialmedia ;;
    Startup) startup ;;
    Timer) timer ;;
    *) exit 1
esac
