#!/usr/bin/env bash

if ! is_command inotifywait; then
    >&2 echo "new_video_notif requires inotifywait"
    exit 1;
elif ! is_command notify-send; then
    >&2 echo "new_video_notif requires notify-send"
    exit 2;
elif ! is_command duration; then
    >&2 echo "new_video_notif requires duration, which is in the same toolbox as this script"
    exit 3;
elif ! is_command du; then
    >&2 echo "new_video_notif requires du"
    exit 4;
elif ! is_command cut; then
    >&2 echo "new_video_notif requires cut"
    exit 5;
fi

inotifywait --monitor --recursive --quiet --format '%w%f' --event close_write "$HOME/Videos/" | while read -r file_path; do
    file_size="$(du -kh "$file_path" | cut -f1)"
    file_duration="$(duration "$file_path")"
    out="Path: $file_path\nSize: $file_size\nDuration: $file_duration"
    echo -e "$out"
    echo
    notify-send "New Video Detected" "$out"
done
