#!/usr/bin/env bash
while true; do
    thing_to_open=$(ls -a | grep -v '^\.$' | fzf --preview 'if [ -d {} ]; then eza -a --icons=always --color=always --group-directories-first --no-quotes {}; else bat --plain --color=always '{}'; fi')
    if (( $? != 0 )); then
        break;
    fi
    if [ -n "$thing_to_open" ]; then
        if [ -d "$thing_to_open" ]; then
            # This is basically the end of the function and it's not going to be called by other functions, so it's ok if cd fails here, if it even can
            # shellcheck disable=SC2164
            cd "$thing_to_open"
        elif [ -f "$thing_to_open" ]; then
            xdg-open "$thing_to_open"
        fi
    fi
done
