#!/usr/bin/env bash
bold_underline="$(tstyle -t bold underline)"
reset="$(tstyle -t reset)"
dim="$(tstyle -t dim)"
highlight="$(tstyle -t 'fg=#ffffff;bg=gray')"
if is_command pacman; then
    echo "${bold_underline}Pacman:$reset"
    echo -e "\tNative Explicit Arch Packages: $(pacman -Qne | wc -l)"
    echo -e "\tNative Dependency Arch Packages: $(pacman -Qnd | wc -l)"
    echo -e "\tAUR Packages: $(pacman -Qm | wc -l)"
    if is_command yay; then
        echo -e "\t$dim(You can do ${highlight}yay -Ps$reset$dim to get more stats about pacman packages)$reset"
    fi
fi

if is_command flatpak; then
    echo "${bold_underline}Flatpak:$reset"
    echo -e "\tFlatpak Apps: $(flatpak list --app | wc -l)"
    echo -e "\tFlatpak Runtimes: $(flatpak list --runtime | wc -l)"
fi

if is_command cargo; then
    echo "Cargo Packages: $(cargo install --list | grep --count :)"
fi

if is_command pipx; then
    echo "pipx packages: $(pipx list | grep --count '^\s*-')"
fi

if is_command pnpm; then
    echo "pnpm packages: $(pnpm list -g | grep --count @)"
fi
