#!/usr/bin/env bash
if ! is_command ffprobe; then
    >&2 echo 'resolution requires ffmpeg/ffprobe'
    exit 4
elif (( $# == 0 )); then
    >&2 echo 'Expected a video or audio file as an argument but got zero arguments'
    exit 1
fi
for arg in "$@"; do
    if [ ! -f "$arg" ]; then
        >&2 echo "$arg is not a valid file"
        exit 3
    fi
    if (( $# > 1 )); then
        tstyle green
        echo -n "$arg: "
        tstyle reset
    fi
    # Just copied from https://superuser.com/a/841379 and changed the filename to "$arg"
    ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "$arg"
done
