#!/usr/bin/env bash
if ! is_command ffprobe; then
    >&2 echo 'resolution requires ffmpeg/ffprobe'
    exit 4
elif (( $# == 0 )); then
    >&2 echo 'Expected a video or audio file as an argument but got zero arguments'
    exit 1
elif (( $# > 1 )); then
    >&2 echo 'Expected only one argument (a video or audio file) but got multiple'
    exit 2
elif [ ! -f "$1" ]; then
    >&2 echo "$1 is not a valid file"
    exit 3
fi
# Just copied from https://superuser.com/a/841379 and changed the filename to "$1"
ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "$1"
