#!/usr/bin/env bash

# Can't use files with colons in the name since colons are used as separators, but I don't think this will negatively affect things often
file_number_line="$(find -type f | sort | grep -v :  | while read file; do
    cat --number "$file" | while read line; do
        line_number="$(echo "$line" | cut -d'	' -f1)"
        if is_command bat; then
            line="$(bat --color=always --plain --line-range "$line_number" "$file")"
        else
            line="$(echo "$line" | cut -d'	' -f2-)"
        fi
        echo -en "$(tstyle -t green)$file$(tstyle -t gray):$line_number\t"
        # Separation so the line isn't affected by the -e. -n is to make it so the separation isn't visible
        echo "$(tstyle -t reset)$line"
    done
done | fzf --ansi --reverse)"

if [ -n "$file_number_line" ]; then
    file="$(echo "$file_number_line" | cut -d':' -f1)"
    number="$(echo "$file_number_line" | cut -d':' -f2 | cut -f1)"

    nvim +$number $file
fi
