#!/usr/bin/env bash
eval "$(echo -e 'asciiquarium\ngitlogue\nlavat -G -c red\nlavat -G -c blue\nlavat -G -c yellow\nlavat -G -c green\nlavat -G -c cyan\nlavat -G -c magenta\nlavat -G -c white\nlavat -G -c black\ntarts boids\ntarts crab\ntarts cube\ntarts donut\ntarts fire\ntarts life\ntarts matrix\ntarts maze\ntarts pipes\ntarts plasma\nterminal-toys ant --pattern=0 --n-c olors=3\nterminal-toys balls\nterminal-toys bubble\nterminal-toys cube\nterminal-toys life --seed=$RANDOM\nterminal-toys pipes3d --seed $RANDOM --rotate\nterminal-toys sand --seed $RANDOM --obstacles=255\nterminal-toys splits --seed $RANDOM\nterminal-toys tunnel' | fzf --layout reverse)"


