#!/usr/bin/env bash
if ! is_command 7z; then
    >&2 echo 'store requires 7z'
    exit 4;
elif (( $# == 0 )); then
    >&2 echo "Expected an argument (a file or directory), but didn't get one"
    exit 1;
elif (( $# > 1 )); then
    >&2 echo "Expected only 1 argument, got $#"
    exit 2;
elif [ ! -f "$1" ] && [ ! -d "$1" ]; then
    >&2 echo "$1 is not a valid file or directory"
    exit 3;
fi
7z a -tzip -mx0 "${1%/}.zip" "${1}"
