#!/usr/bin/env bash

# Based on using whisper.cpp on Arch Linux on an AMD GPU

if ! is_command whisper-cli; then
    >&2 echo 'transcribe requires whisper.cpp'
    exit 3
elif (( $# == 0 )); then
    >&2 echo 'Expected at least one video or audio file but got zero arguments'
    exit 1
fi

for arg in "$@"; do
    if [ ! -f "$arg" ]; then
        >&2 echo "\"$arg\" is not a valid file"
        exit 2
    elif [ "${arg: -4}" != '.wav' ] && ! is_command ffmpeg; then
        >&2 echo "To transcribe a file that isn't a .wav file, this script needs ffmpeg installed so it can convert it"
        exit 4
    fi
done

for arg in "$@"; do

    file_to_transcribe="$arg"

    # If last 4 characters aren't ".wav"
    if [ "${arg: -4}" != '.wav' ]; then
        with_wav="$arg.wav"
        # -f checks if a file exists
        if [ -f "$with_wav" ]; then
            file_to_transcribe="$with_wav"
        else
            without_extension_with_wav="$(echo $arg | without_last_extension).wav"
            if [ -f "$without_extension_with_wav" ]; then
                file_to_transcribe="$without_extension_with_wav"
            else
                ffmpeg -i "$arg" "$with_wav"
                file_to_transcribe="$with_wav"
            fi
        fi
    fi
    whisper-cli --model "$HOME/whisper.cpp models/ggml-large-v3-turbo.bin" "$file_to_transcribe" | whisper_transcript_to_srt | tee "$file_to_transcribe.srt"
done
