#!/usr/bin/env sh

if is_command eos-update; then
    eos-update
elif is_command yay; then
    yay
elif is_command pacman; then
    pacman -Syu
fi

if is_command rustup; then
    rustup update stable
fi
if is_command cargo; then
    # https://stackoverflow.com/a/66049504/10821659 with `egrep` replaced with `grep -E`
    cargo install $(cargo install --list | grep -E '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' ')
fi

if is_command flatpak; then
    flatpak update
fi
