#!/usr/bin/env sh
if ! is_command reflector; then
    >&2 echo "This script is made for EndeavourOS and reflector can't be found"
    exit 1
elif ! is_command eos-rankmirrors; then
    >&2 echo "This script is made for EndeavourOS and eos-rankmirrors can't be found"
    exit 2
fi

mirror_count=50

sudo reflector --verbose --protocol https --latest $mirror_count --sort rate --save /etc/pacman.d/mirrorlist 2>&1 | llc --total=$mirror_count --count-filter="INFO: https:" --after
eos-rankmirrors
