#!/usr/bin/env sh

if is_command eos-update; then
    if is_command yay; then
        eos-update --yay
    elif is_command paru; then
        eos-update --paru
    else
        eos-update
    fi
elif is_command yay; then
    yay
elif is_command paru; then
    paru
elif is_command pacman; then
    pacman -Syu
fi

if is_command rustup; then
    rustup update stable
fi
if is_command cargo; then
    # https://stackoverflow.com/a/66049504 with `egrep` replaced with `grep -E`
    cargo install $(cargo install --list | grep -E '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' ')
fi

if is_command flatpak; then
    flatpak update
fi

if is_command pipx; then
    pipx upgrade-all
fi
