#!/usr/bin/env sh
if is_command eos-update; then
    if is_command yay; then
        eos-update --yay
    elif is_command paru; then
        eos-update --paru
    else
        eos-update
    fi
elif is_command yay; then
    yay
elif is_command paru; then
    paru
elif is_command pacman; then
    pacman -Syu
fi

if is_command rustup; then
    rustup update stable
fi

commands=""

if is_command cargo; then
    # https://stackoverflow.com/a/66049504 with `egrep` replaced with `grep -E`
    commands="$commands -c 'cargo install $(cargo install --list |
        grep -E '^[a-z0-9_-]+ v[0-9.]+:$' |
        cut -f1 -d' ' | tr '\n' ' ')'"
fi

if is_command flatpak; then
    commands="$commands -c 'flatpak update --assumeyes --noninteractive'"
fi

if is_command pipx; then
    commands="$commands -c 'pipx upgrade-all'"
fi

if is_command pnpm; then
    commands="$commands -c 'pnpm update --global'"
fi

eval "noscroll $commands"
